language: cpp
sudo: false
dist: trusty

services: mongodb

addons:
  apt:
    packages: &common_packages
      - gdb

matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: CONFIG=Debug
      addons: &common_addons
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse"
              key_url: "https://www.mongodb.org/static/pgp/server-3.4.asc"
          packages: [ mongodb-org-server, mongodb-org-shell, *common_packages ]
    - compiler: gcc
      env: CONFIG=Release
      addons: *common_addons
    - compiler: clang
      env: CONFIG=Debug
      addons: *common_addons
    - compiler: clang
      env: CONFIG=Release
      addons: *common_addons

before_install:
    # Mongo C Driver
    - git clone https://github.com/mongodb/mongo-c-driver.git

install:
    # Install Mongo C Driver
    - pushd mongo-c-driver

    - git checkout 1.8.1
    - git submodule update --init --recursive
    - $CC --version
    - $CXX --version
    - which clang
    - export CC=`which $CC`
    - export CXX=`which $CXX`
    - ./autogen.sh --disable-automatic-init-and-cleanup --enable-tests=no --enable-examples=no --with-libbson=bundled; make; sudo make install

    - popd

before_script:
    - $CC --version
    - $CXX --version

    - ./.travis.sh

    # Build the driver and the tests
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_C_FLAGS="-Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers" -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers" ..

script:
    - make format-lint

    - make all

    # Run bsoncxx tests with catch
    - ./src/bsoncxx/test/test_bson

    # Run mongocxx tests with catch
    - ./src/mongocxx/test/test_driver

    # Run mongocxx instance tests with catch
    - ./src/mongocxx/test/test_instance

    # Install headers and libs for the examples
    #- make install

    # Make the examples
    #- make examples

    # Run the examples
    #- make run-examples
